### ISSUE TITLE
Implicit type 'any' on function properties

### ISSUE THREAD

**Issue by pmqueiroz** [MatheusSESH/comms-app#1]
Your [ `function cardList`](https://github.com/MatheusSESH/comms-app/blob/005b03cb60116968f0d4cb8b9b2f6e19225203a4/comms-mobile/src/pages/teacher-pages/dashboard/home.tsx#L60)  properties must have the same type defined on [state](https://github.com/MatheusSESH/comms-app/blob/005b03cb60116968f0d4cb8b9b2f6e19225203a4/comms-mobile/src/pages/teacher-pages/dashboard/home.tsx#L15).

https://github.com/MatheusSESH/comms-app/blob/005b03cb60116968f0d4cb8b9b2f6e19225203a4/comms-mobile/src/pages/teacher-pages/dashboard/home.tsx#L15

https://github.com/MatheusSESH/comms-app/blob/005b03cb60116968f0d4cb8b9b2f6e19225203a4/comms-mobile/src/pages/teacher-pages/dashboard/home.tsx#L60

Replace your properties type on cardList function for 
```ts
function cardList({ item }: { item: DataProps}) {
        { ... }
}
```

_Tip:_ Use `CardProps` instead of `DataProps`

**Comment by MatheusViniciussv** [comment]
Thanks! I'll fix that :)
